# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 15.x
      uses: actions/setup-node@v2
      with:
        node-version: 15.x
    - uses: microsoft/playwright-github-action@v1
    - run: npm ci
    - run: CI='' npm run build --if-present
    - run: npm test
    - run: npm install playwright
    - name: run CodeceptJS tests
      run: |
        npx codeceptjs run --override '{"helpers": {"Playwright": {"show": false}}}'
